-- 排产任务表
CREATE TABLE FR_CX_SCHEDULE_TASK (
  ID          VARCHAR2(13)    NOT NULL,   -- 毫秒时间戳，如 1743300000000
  DISPLAY     VARCHAR2(200)   NOT NULL,
  PRODUCT     VARCHAR2(100)   NOT NULL,
  MACHINE     VARCHAR2(100)   NOT NULL,
  TYPE        VARCHAR2(10)    NOT NULL,
  START_DATE  TIMESTAMP       NOT NULL,
  DURATION    NUMBER          NOT NULL,   -- 分钟，含 JOBCHANGE
  QTY         NUMBER          NOT NULL,   -- 片数
  TT          NUMBER          NOT NULL,   -- 秒/片
  JOBCHANGE   NUMBER          DEFAULT 0,  -- 换机时间（分钟）
  CREATE_TIME DATE            DEFAULT SYSDATE,
  UPDATE_TIME DATE            DEFAULT SYSDATE,
  CONSTRAINT PK_FR_CX_SCHEDULE_TASK PRIMARY KEY (ID)
);

-- 注释
COMMENT ON TABLE  FR_CX_SCHEDULE_TASK            IS '排产甘特图任务表';
COMMENT ON COLUMN FR_CX_SCHEDULE_TASK.ID         IS '任务ID（毫秒时间戳字符串）';
COMMENT ON COLUMN FR_CX_SCHEDULE_TASK.DISPLAY    IS '任务条显示内容';
COMMENT ON COLUMN FR_CX_SCHEDULE_TASK.PRODUCT    IS '产品型号（CELL_NO）';
COMMENT ON COLUMN FR_CX_SCHEDULE_TASK.MACHINE    IS '设备（DEVICE）';
COMMENT ON COLUMN FR_CX_SCHEDULE_TASK.TYPE       IS '生产模式 1/2/3';
COMMENT ON COLUMN FR_CX_SCHEDULE_TASK.START_DATE IS '开始时间';
COMMENT ON COLUMN FR_CX_SCHEDULE_TASK.DURATION   IS '总时长（分钟，含换机时间）';
COMMENT ON COLUMN FR_CX_SCHEDULE_TASK.QTY        IS '生产片数';
COMMENT ON COLUMN FR_CX_SCHEDULE_TASK.TT         IS 'TT秒/片';
COMMENT ON COLUMN FR_CX_SCHEDULE_TASK.JOBCHANGE  IS '换机时间（分钟）';
